@TodoApi_HostAddress = http://localhost:5047

# Paste your JWT token here after login
@Token =
POST {{TodoApi_HostAddress}}/authentication/login 
Content-Type: application/json

{
    "username": "admin",
    "password": "1234"
}


### 🔒 GET - Without Token
GET {{TodoApi_HostAddress}}/weatherforecast/
Accept: application/json


### 🔐 GET - With JWT Token
GET {{TodoApi_HostAddress}}/weatherforecast
Authorization: Bearer {{Token}}
Accept: application/json


### 🔐 GET - Get by ID
GET {{TodoApi_HostAddress}}/weatherforecast/1
Authorization: Bearer {{Token}}
Accept: application/json


### 🔐 POST - Create
POST {{TodoApi_HostAddress}}/weatherforecast
Authorization: Bearer {{Token}}
Content-Type: application/json

{
    "date": "2026-09-28",
    "temperatureC": 25,
    "summary": "Warm"
}


### 🔐 PUT - Update
PUT {{TodoApi_HostAddress}}/weatherforecast/1
Authorization: Bearer {{Token}}
Content-Type: application/json

{
    "date": "2026-09-28",
    "temperatureC": 30,
    "summary": "Hot"
}


### 🔐 DELETE - Delete
DELETE {{TodoApi_HostAddress}}/weatherforecast/1
Authorization: Bearer {{Token}}
Accept: application/json